name: Check Python syntax

env:
  SCRIPT_FILE: syncDirectories.py

on:
  workflow_call:
    inputs:
      script:
        required: true
        type: string

jobs:
  check:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check Python syntax
        run: |
          echo ${{ env.SCRIPT_FILE }}
          python -m py_compile ${{ env.SCRIPT_FILE }}
