name: Check and Release Python

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:
    branches: [master]

env:
  SCRIPT_FILE: syncDirectories.py

jobs:
  check-syntax:
    name: Check Python Syntax
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check Python syntax
        run: |
          echo ${{ env.SCRIPT_FILE }}
          python -m py_compile ${{ env.SCRIPT_FILE }}

  publish:
    name: Publish Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: check-syntax
    runs-on: windows-2022
    outputs:
      output-path: ${{ steps.upload.outputs.upload-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create GitHub Release and Upload Asset
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Sync Directories ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: ${{ env.SCRIPT_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
