name: Build and Release .NET Framework Desktop App

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:
    branches: [master]

env:
  SCRIPT_FILE: syncDirectories.py

jobs:

  check-syntax:
    uses: ./.github/workflows/check-python.yml
    with:
      script: ${{ env.SCRIPT_FILE }}

  publish:
    name: Publish
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release-python.yml
    with:
      script: ${{ env.SCRIPT_FILE }}
