name: Release Python Script

on:
  workflow_call:
    inputs:
      script:
        required: true
        type: string

    outputs:
      output-path:
        description: "Build output path"
        value: ${{ jobs.release.outputs.output-path }}

jobs:
  release:
    runs-on: windows-2022
    outputs:
      output-path: ${{ steps.upload.outputs.upload-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create GitHub Release and Upload Asset
        id: upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Sync Directories ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: ${{ inputs.script }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
